/**
 * Turns out/ into a single TypeScript module of base64 blobs.
 *
 * `deno compile --include` can embed a directory, but then the runtime has to
 * resolve paths inside the binary, which differs by platform. Baking the files
 * into the module removes that whole class of problem: the server just serves
 * from memory and cross-compiled targets behave identically.
 */
import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const out = path.join(root, "out");
const target = path.join(root, "server", "assets.ts");

if (!fs.existsSync(out)) {
  console.error("no out/ — run `npm run build:static` first");
  process.exit(1);
}

const TYPES = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".ico": "image/x-icon",
  ".png": "image/png",
  ".woff2": "font/woff2",
  ".txt": "text/plain; charset=utf-8",
};

const files = [];
(function walk(dir) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p);
    else files.push(p);
  }
})(out);

let total = 0;
const entries = files.map((f) => {
  const rel = "/" + path.relative(out, f).split(path.sep).join("/");
  const buf = fs.readFileSync(f);
  total += buf.length;
  const type = TYPES[path.extname(f).toLowerCase()] ?? "application/octet-stream";
  return `  ${JSON.stringify(rel)}: { type: ${JSON.stringify(type)}, b64: "${buf.toString("base64")}" },`;
});

fs.mkdirSync(path.dirname(target), { recursive: true });
fs.writeFileSync(
  target,
  `// GENERATED by scripts/embed-assets.mjs — do not edit.\n` +
    `export interface Asset { type: string; b64: string }\n` +
    `export const ASSETS: Record<string, Asset> = {\n${entries.join("\n")}\n};\n`,
);

console.log(
  `embedded ${files.length} files, ${(total / 1e6).toFixed(2)} MB raw ` +
    `-> server/assets.ts (${(fs.statSync(target).size / 1e6).toFixed(2)} MB)`,
);
